name: blinker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.10
  lottie: ^3.1.3
  smooth_page_indicator: ^1.2.0+3
  draggable_home: ^1.0.5
  speech_to_text: ^7.0.0
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
    - assets/anim/
    - assets/anim/anim_2.json

    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  adaptive_icon_foreground: "assets/images/logo.jpeg"
  adaptive_icon_background: "#ffffff"
